#
# Blog Settings
#
author: 'Ankit Rana'
title: Your awesome title
email: ankit.rana.1195@gmail.com
defaultbackground: '/assets/images/backdrop.jpg'
description: >- # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
url: "" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  code-atom


# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-redirect-from
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-paginate

#
# Jekyll Settings
#
permalink: /posts/:year/:month/:day/:title
paginate: 20
paginate_path: "page/:num"
category_dir: categories
